### ISSUE TITLE
Output of anycomplete does not apply to mac osx applications

### ISSUE THREAD

**Issue by fogonthedowns** [nathancahill/anycomplete#13]
Repo steps:

1. Open terminal on 10.11.6 (15G31) OSX
2. Use anycomplete
3 Press command 1
4. notice that output does not appear in application

Welcome to the Hammerspoon Console!
You can run any Lua code in here.

-- Lazy extension loading enabled
-- Loading ~/.hammerspoon/init.lua
-- Loading extension: hotkey
09:00:31     hotkey: Enabled hotkey ⌘⌃⌥G
-- Done.
-- Loading extension: application
-- Loading extension: uielement
-- Loading extension: chooser
-- Loading extension: http
-- Loading extension: json
-- Loading extension: eventtap
-- Loading extension: fnutils

**Comment by nathancahill** [comment]
Merging this issue with #8.
