### ISSUE TITLE
Doesn't work with fullscreen applications

### ISSUE THREAD

**Issue by jorgemmsilva** [nathancahill/Anycomplete#15]
Everything doing as intended, however it's not working when using a text editor in fullscreen mode (macOS Sierra 10.12.1). Tried using Atom and TextEdit, it simply creates the GUI in the original desktop.

^this is probably working as intended, but it could be a nice feature to have

**Comment by jorgemmsilva** [comment]
its possible to add this to the hotkey function, it kinda works, but the behaviour isn't the best

```
local win = hs.window.focusedWindow()
    if win ~= nil then
        win:setFullScreen(not win:isFullScreen())
    end
```

**Comment by nathancahill** [comment]
Maybe best to open an issue on the Hammerspoon repo?
