### ISSUE TITLE
Press tab to expand the result similar to Alfred

### ISSUE THREAD

**Issue by nikitavoloboev** [nathancahill/Anycomplete#19]
![2016-12-03 at 11 16](https://cloud.githubusercontent.com/assets/6391776/20858639/eeba2fd2-b949-11e6-82f3-1ed0c561cb57.png)

![2016-12-03 at 11 14](https://cloud.githubusercontent.com/assets/6391776/20858635/d976d530-b949-11e6-82ba-fb82267ba02b.png)

**Comment by nathancahill** [comment]
@oleander fixed this in #20.
