### ISSUE TITLE
I get module urlencode not found error

### ISSUE THREAD

**Issue by nikitavoloboev** [nathancahill/Anycomplete#22]
I tried reinstalling the Anycomplete module to get the new changes but now I get the following error : 

![2016-12-04 at 11 27](https://cloud.githubusercontent.com/assets/6391776/20865495/9ffa1b02-ba14-11e6-8eb4-193894a76785.png)

Here it is in text : 

```Bash
*** ERROR: ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:449: module 'urlencode' not found:
	no field package.preload['urlencode']
	no file '/Users/nikivi/.hammerspoon/urlencode.lua'
	no file '/Users/nikivi/.hammerspoon/urlencode/init.lua'
	no file '/usr/local/share/lua/5.3/urlencode.lua'
	no file '/usr/local/share/lua/5.3/urlencode/init.lua'
	no file '/usr/local/lib/lua/5.3/urlencode.lua'
	no file '/usr/local/lib/lua/5.3/urlencode/init.lua'
	no file './urlencode.lua'
	no file './urlencode/init.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/urlencode.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/urlencode/init.lua'
	no file '/Users/nikivi/.hammerspoon/urlencode.so'
	no file '/usr/local/lib/lua/5.3/urlencode.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './urlencode.so'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/urlencode.so'
stack traceback:
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:449: in function 'require'
	/Users/nikivi/.hammerspoon/init.lua:15: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:481: in function 'hs._coresetup.setup'
	(...tail calls...)
```

Where do I get this module from? This plugin was working really well before I tried reinstalling it.

**Comment by oleander** [comment]
If you close Hammerspoon and start it again, when does the error occur? On start-up, `cmd-c`, `tab` or when searching?

Also, could you upload your `init.lua` file?

**Comment by nikitavoloboev** [comment]
It occurs on startup even : 

![2016-12-04 at 11 36](https://cloud.githubusercontent.com/assets/6391776/20865549/e1913c66-ba15-11e6-99a7-d7fb9072b184.png)

[This](https://github.com/nikitavoloboev/dotfiles/blob/master/hammerspoon/init.lua) is my init.lua file.

**Comment by oleander** [comment]
Could you try removing `local urlencode = require("urlencode")` from your `init.lua` file and restart?

**Comment by nikitavoloboev** [comment]
Thank you @oleander. It works great now.

**Comment by oleander** [comment]
Awesome!

**Comment by nikitavoloboev** [comment]
Can you help me make a small fork to this already awesome module. I want to search on a result in google with a modifier key. Like the issue I created [here](https://github.com/nathancahill/Anycomplete/issues/3).

**Comment by nikitavoloboev** [comment]
Is this possible to do still? 

I really wish I could add it. :( 

Thank you for any help.
