### ISSUE TITLE
Default keybinding don't seem to be working

### ISSUE THREAD

**Issue by arronmabrey** [nathancahill/Anycomplete#24]
Hey all,

I'm doing a fresh install on the latest macOS 10.12.1 and the default key binding of "CTL + ALT + CMD + g" doesn't seem to be doing anything.

Any thoughts?

Thanks,
-- Arron

**Comment by nathancahill** [comment]
Check that Hammerspoon is enabled in Accessability. Look at the Hammerspoon console for any messages (or lack of, you should see 4-5 lines of "extension loaded" when you press the keys).

**Comment by arronmabrey** [comment]
I did have the Accessibility enabled, but I didn't have a `~/.hammerspoon/init.lua`
So I ran `touch ~/.hammerspoon/init.lua`, and reloaded the config. 

I also git cloned anycomplete into `.hammerspoon`. 

```
mpb:~/.hammerspoon:-> tree
.
├── anycomplete
│   ├── README.md
│   ├── anycomplete.lua
│   ├── init.lua
│   └── install.sh
└── init.lua

1 directory, 5 files
```

When trying the default keybindings the console is not printing anything new.

```
Welcome to the Hammerspoon Console!
You can run any Lua code in here.

-- Lazy extension loading enabled
-- Loading extension: notify
-- Loading extension: fnutils
-- Can't find ~/.hammerspoon/init.lua; create it and reload your config.
-- Lazy extension loading enabled
-- Loading ~/.hammerspoon/init.lua
-- Done.
-- Lazy extension loading enabled
-- Loading ~/.hammerspoon/init.lua
-- Done.
-- Lazy extension loading enabled
-- Loading ~/.hammerspoon/init.lua
-- Done.
```

**Comment by nathancahill** [comment]
Did you add these lines to your init.lua? https://github.com/nathancahill/anycomplete#manual-installation

**Comment by arronmabrey** [comment]
Wow, I totally missed that.

Sorry about that, I'm usually very diligent about RTFM... 

Thanks!
