### ISSUE TITLE
Modifier Key press like control + return to actually search for the term on google in a browser

### ISSUE THREAD

**Issue by nikitavoloboev** [nathancahill/anycomplete#3]
This extension is phenomenal and is extremely useful, what would make it more useful is to allow the user to press a modifier key press on a search term and make a search in google in the default browser of the user.

**Comment by nathancahill** [comment]
I'm going to keep this config simple. If you want to do that on your machine, the lines to change are: https://github.com/nathancahill/anycomplete/blob/master/anycomplete.lua#L10

**Comment by pdaddyo** [comment]
@nikitavoloboev My fork adds this feature (to shift key).  Only seems to work for the first result though (pressing shift+enter), and you'll want to tweak the google url to your country for local results.  https://github.com/pdaddyo/anycomplete

**Comment by nikitavoloboev** [comment]
@pdaddyo just tried your fork and it didn't work for me for some reason :(
