### ISSUE TITLE
Use ctrl+p/ctrl+n to move up and down the list

### ISSUE THREAD

**Issue by stiang** [nathancahill/anycomplete#9]
It would be great if it were possible to use ctrl+p and ctrl+n to move the selection up/down, in addition to the arrow keys. This is the standard Emacs keybinding for moving up/down, which is also supported by default in macOS, bash etc.

**Comment by selectnull** [comment]
@stiang I agree that this would be desirable behaviour, but it should be implemented in [Hammerspoon](https://github.com/Hammerspoon/hammerspoon) itself, not in `anycomplete` as it simply uses built in chooser functionality.

**Comment by stiang** [comment]
@selectnull Ah, agreed. Closing this issue and creating one there instead.
